ALTER TABLE "ArenaUnit" ADD COLUMN IF NOT EXISTS "parentUnitId" TEXT;
ALTER TABLE "ArenaUnit" ADD CONSTRAINT "ArenaUnit_parentUnitId_fkey" FOREIGN KEY ("parentUnitId") REFERENCES "ArenaUnit"("id") ON DELETE SET NULL ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
