steps:
  # Build the studio Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/swing/studio:$COMMIT_SHA
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/swing/studio:latest
      - .

  # Push to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-south1-docker.pkg.dev/$PROJECT_ID/swing/studio:$COMMIT_SHA

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-south1-docker.pkg.dev/$PROJECT_ID/swing/studio:latest

images:
  - asia-south1-docker.pkg.dev/$PROJECT_ID/swing/studio:$COMMIT_SHA
  - asia-south1-docker.pkg.dev/$PROJECT_ID/swing/studio:latest

options:
  logging: CLOUD_LOGGING_ONLY
