// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy1bjfhqq5OheY5K3-CnQhBBC2HEn9-ko',
    appId: '1:594513906251:web:a2a1f123fd1e138ce41bce',
    messagingSenderId: '594513906251',
    projectId: 'swing-35d52',
    authDomain: 'swing-35d52.firebaseapp.com',
    storageBucket: 'swing-35d52.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa9s9t5nGb_RZqsYrhcFdpJMJB_3XbF0U',
    appId: '1:594513906251:android:28ba65295b27a1dee41bce',
    messagingSenderId: '594513906251',
    projectId: 'swing-35d52',
    storageBucket: 'swing-35d52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_YhSxMbQvZhRgQmssZNvuAbNr3iOE56Y',
    appId: '1:594513906251:ios:b3bf34726724f6b0e41bce',
    messagingSenderId: '594513906251',
    projectId: 'swing-35d52',
    storageBucket: 'swing-35d52.firebasestorage.app',
    iosBundleId: 'com.swing.swingBiz',
  );
}
