-- Swing Index v2 persistence fields on aggregate table
ALTER TABLE "player_index_aggregate"
  ADD COLUMN IF NOT EXISTS "currentSwingIndexScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "swingFormulaVersion" TEXT NOT NULL DEFAULT 'swing-index-v2',
  ADD COLUMN IF NOT EXISTS "swingBatScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "swingBowlScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "swingFieldingImpact" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "swingPowerScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "swingImpactScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "swingAxes" JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS "swingSubScores" JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS "swingDerivedMetrics" JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS "swingWeightingMeta" JSONB NOT NULL DEFAULT '{}'::jsonb;
