ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "motto"          TEXT;
ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "homeGroundName" TEXT;
ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "foundedYear"    INTEGER;
ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "ageGroup"       TEXT;
ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "format"         TEXT;
ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "skillLevel"     TEXT;
ALTER TABLE "Team" ADD COLUMN IF NOT EXISTS "isPublic"       BOOLEAN NOT NULL DEFAULT true;
